export const ADMIN_THEME = {
  colors: {
    page: '#F4F6F8',
    surface: '#FFFFFF',
    surfaceMuted: '#F8FAF9',
    text: '#1C2720',
    textStrong: '#303A34',
    textBody: '#47524B',
    textMuted: '#7B857E',
    textSubtle: '#929A95',
    border: '#E0E5E2',
    borderSoft: '#E8ECE9',
    green: '#4CAF50',
    greenDark: '#237A3B',
    greenSoft: '#EAF8EE',
    red: '#B42318',
    redSoft: '#FFF3F2',
  },
  fonts: {
    regular: 'mon',
    semibold: 'mon-sb',
    bold: 'mon-b',
  },
  sizes: {
    caption: 8,
    label: 9,
    body: 10,
    control: 11,
    subtitle: 12,
    section: 14,
    metric: 23,
    title: 30,
  },
  radius: {
    control: 11,
    card: 15,
    panel: 18,
    pill: 99,
  },
  layout: {
    maxWidth: 1548,
    pagePadding: 24,
    pageBottomPadding: 56,
    pageGap: 18,
    gridGap: 12,
    controlHeight: 42,
    tableHeaderHeight: 45,
    tableRowHeight: 72,
  },
} as const;

export const ADMIN_SHARED_STYLES = {
  page: { flex: 1, backgroundColor: ADMIN_THEME.colors.page },
  pageContent: {
    width: '100%' as const,
    maxWidth: ADMIN_THEME.layout.maxWidth,
    alignSelf: 'center' as const,
    padding: ADMIN_THEME.layout.pagePadding,
    paddingBottom: ADMIN_THEME.layout.pageBottomPadding,
    gap: ADMIN_THEME.layout.pageGap,
  },
  pageHeader: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    alignItems: 'flex-end' as const,
    justifyContent: 'space-between' as const,
    gap: 16,
  },
  eyebrow: {
    fontFamily: ADMIN_THEME.fonts.bold,
    fontSize: ADMIN_THEME.sizes.label,
    letterSpacing: 1.4,
    color: '#2C9C5B',
    marginBottom: 7,
  },
  pageTitle: {
    fontFamily: ADMIN_THEME.fonts.bold,
    fontSize: ADMIN_THEME.sizes.title,
    color: ADMIN_THEME.colors.text,
    marginBottom: 7,
  },
  pageSubtitle: {
    fontFamily: ADMIN_THEME.fonts.regular,
    fontSize: ADMIN_THEME.sizes.subtitle,
    lineHeight: 19,
    color: '#737D77',
  },
  statsGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: ADMIN_THEME.layout.gridGap,
  },
  statCard: {
    flex: 1,
    minWidth: 170,
    minHeight: 116,
    padding: 15,
    borderWidth: 1,
    borderColor: '#E5EAE7',
    borderRadius: ADMIN_THEME.radius.card,
    backgroundColor: ADMIN_THEME.colors.surface,
  },
  statIcon: {
    width: 35,
    height: 35,
    borderRadius: ADMIN_THEME.radius.control,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  statLabel: {
    fontFamily: ADMIN_THEME.fonts.semibold,
    fontSize: ADMIN_THEME.sizes.label,
    color: ADMIN_THEME.colors.textMuted,
    marginTop: 9,
  },
  statValue: {
    fontFamily: ADMIN_THEME.fonts.bold,
    fontSize: ADMIN_THEME.sizes.metric,
    color: '#202B24',
    marginTop: 4,
  },
  filter: {
    minHeight: 37,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 7,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: ADMIN_THEME.colors.border,
    borderRadius: 10,
    backgroundColor: ADMIN_THEME.colors.surface,
  },
  filterActive: {
    borderColor: ADMIN_THEME.colors.green,
    backgroundColor: ADMIN_THEME.colors.greenSoft,
  },
  filterText: {
    fontFamily: ADMIN_THEME.fonts.semibold,
    fontSize: ADMIN_THEME.sizes.label,
    color: '#66716A',
  },
  filterTextActive: { color: ADMIN_THEME.colors.greenDark },
  searchBox: {
    minWidth: 260,
    minHeight: ADMIN_THEME.layout.controlHeight,
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 9,
    borderWidth: 1,
    borderColor: '#DDE3DF',
    borderRadius: 12,
    paddingHorizontal: 13,
    backgroundColor: ADMIN_THEME.colors.surface,
  },
  searchInput: {
    flex: 1,
    minWidth: 120,
    fontFamily: ADMIN_THEME.fonts.regular,
    fontSize: ADMIN_THEME.sizes.control,
    color: '#27332B',
  },
  refreshButton: {
    width: ADMIN_THEME.layout.controlHeight,
    height: ADMIN_THEME.layout.controlHeight,
    borderRadius: ADMIN_THEME.radius.control,
    borderWidth: 1,
    borderColor: '#DDE3DF',
    backgroundColor: ADMIN_THEME.colors.surface,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  tableHeader: {
    minHeight: ADMIN_THEME.layout.tableHeaderHeight,
    backgroundColor: ADMIN_THEME.colors.surfaceMuted,
  },
  tableHeaderText: {
    fontFamily: ADMIN_THEME.fonts.bold,
    fontSize: ADMIN_THEME.sizes.caption,
    color: '#59645D',
  },
  tableCell: {
    fontFamily: ADMIN_THEME.fonts.regular,
    fontSize: ADMIN_THEME.sizes.body,
    color: ADMIN_THEME.colors.textBody,
  },
  tableStrong: {
    fontFamily: ADMIN_THEME.fonts.semibold,
    fontSize: ADMIN_THEME.sizes.body,
    color: '#27322B',
  },
  buttonText: {
    fontFamily: ADMIN_THEME.fonts.semibold,
    fontSize: ADMIN_THEME.sizes.label,
    color: '#626D66',
  },
} as const;
