name: Auto Lint Fix (Monorepo)

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [chefin_app]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
          npm ci
        working-directory: ${{ matrix.folder }}

      - name: Run ESLint with auto-fix
        run: npm run lint -- --fix
        working-directory: ${{ matrix.folder }}

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix lint errors in ${{ matrix.folder }}"
          git push
